### ISSUE TITLE
40-frontend-my-account

### ISSUE THREAD

**Issue by lindsaynaki** [2110-FTB-PT/infinite-loop#106]
Story: As users, we would like to have a "my account" tab to see of our orders with status/order information. We also would like to be cancel/update the existing orders.

Implementation:
- [x] My Order tab shows all the orders user has (if they are signed in)
- [x] My Order tab allows registered users to pull up order by orderId
- [x] Registered Users are able to edit the orders
- [x] Registered Users are able to delete the orders 
- [x] Above tabs will only show when users are logged in instead of login/register form
- [x] Edit account information 
- [x] My Order tab can show total $ (@yeonjupark95)

**Comment by yeonjupark95** [comment]
rendering total order price @yeonjupark95
