### ISSUE TITLE
42-frontend-cart

### ISSUE THREAD

**Issue by lindsaynaki** [2110-FTB-PT/infinite-loop#108]
Story: As a development team, we would like to have the cart page where orders can be processed.
As users, we want to store items for potential purchase in cart and process the orders from there when ready.

Implementation:
- [x] products are added to cart when clicked on add to cart buttons and stored for the user (issue #107) This logic has been changed to issue #193
- [x] render all the products added to the cart
- [x] users can adjust the quantity in their order in cart page
- [x] users can delete the product in their order in cart page (by either decreasing quantity to zero, or clicking delete)
- [x] render total price
- [x] change shipping price based on Kim's description
- [x] order form (address, email, etc)
- [x] checkout button (with stripe) (issue #93)
- [x] checkout success page (order number, shows summary of order) and update the order status to success
- [x] if users have updated the order form, update the order status to processing  (if they cancel, vice versa)
- [x] if users clicked continue to payment, update the order status to payment pending (if they cancel, vice versa)
- [x] if users login after creating a cart as a guest, reset the cart and create a cart with a correct userId
- [x] after checkout has been successful, create a new cart
- [x] bug: guest cart needs to stay when page is refreshed
- [x] ensure the sequence of products doesn't change after deleting an order
- [x] remove all the functions that ended up not being in use due to logic changes/stripe format changes
- [x] enhancement: the order should also take care of issue #166 
- [x] enhancement: #225 
- [x] #193 
- [x] change the order confirmation url from local to deployed success page
