### ISSUE TITLE
22-db-bugfix

### ISSUE THREAD

**Issue by yeonjupark95** [2110-FTB-PT/infinite-loop#61]
Story: As a development team, we are reviewing Product Manager's comments and making sure that we are following up with the feedback we received from the pull request to Main.

Implementation (the comments we received)
- [x] #89
- [x] api/apiRouter.test.js: always check the boilerplate and make sure that if you aren't using it just delete it #183 
- [x] api/index.js: usually people just have this type of message on their health route rather than keeping it in the /api route #183
- [x] db/client.js: just think about the SSL connection when it comes to the client object.
- [x] db/init_db.js: if you're doing a test file, please double check the client.connect()
- [x] db/models/orders.js: what happens if i receive no orders in this function?
- [x] db/models/orders.js: please do not have console logsss
- [x] db/models/orders.js: cool where clause, but we don't need it. double check if you need this function or not
- [x] db/models/orders.js: so just double check if you need to returning * for any of these db adapters
- [x] db/models/products_orders.js: just becareful with the variable naming
- [x] db/models/reviews.js: test the function if the aliasing will work correctly
- [x] index.js: boilerplate code: if you're not gonna use it, delete it #183 
- [x] api/utils.js: Rethink this function, because if you know that this function returns as false, you will always next the same error object.
